### ISSUE TITLE
Dynamic require of "path" is not supported

### ISSUE THREAD

**Issue by linesoft2** [sxzz/unplugin-glob#2] opened 2023-03-10 12:03 UTC
### Describe the bug

Specifying `"type": "module"` in package.json will cause an error: `Dynamic require of "path" is not supported`
You can refer to this issue: Subwaytime/vite-aliases#33

### Reproduction

Don't need

### System Info

```Shell
Don't need
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment] 2023-03-10 12:54
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

https://antfu.me/posts/why-reproductions-are-required

**Closed by sxzz** 2023-03-10 12:54 UTC
